services:
  api:
    image: palikezy/ringier-assignment-app:latest
    environment:
      - OLLAMA_URL=http://ollama:11434
    env_file:
      - .env
    ports:
      - "80:80"

  ollama:
    image: palikezy/ringier-assignment-ollama:latest
    env_file:
      - .env
